name: zipf
channels:
  
dependencies:
  - numpy= 1.20.3
  - numpy-base= 1.20.3 and 1.0.4
  - pandas= (1.3.4), (2.8.2) (1.20.3) (1.16.0)
  - pango= 0.7.6
  - pillow= 8.4.0
  - pip= 22.0.2+dfsg-1
  - scikit-learn=0.24.2=py38ha9443f7_0
  - scipy= 1.8.1 and 1.20.3
  - seaborn= 0.11.2
  - setuptools= 58.0.4
  - six= 1.16.0
